version: '3.9'
services:
  socialserver:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "rrs/socialserver:1.0.0"
    volumes:
      - /root/wa/session/tmp:/app/session/tmp
      - /root/wa/session/login:/app/session/login
      - /root/wa/logs:/app/logs
    environment:
      - SOCIALSERVER_DB_HOST=103.148.151.67
      - SOCIALSERVER_DB_PORT=5432
      - SOCIALSERVER_DB_USERNAME=postgres
      - SOCIALSERVER_DB_PASSWORD=whsafv@
      - SOCIALSERVER_DB_DATABASE=what
      - SOCIALSERVE_LOG_OUTPUT_PATHS=/app/logs/SOCIALSERVE.log,stdout
      - SOCIALSERVER_INSECURE_BIND_ADDRESS=0.0.0.0
      - SOCIALSERVER_SECURE_BIND_ADDRESS=0.0.0.0
      - SOCIALSERVER_INSECURE_BIND_PORT=8808
      - SOCIALSERVER_SECURE_BIND_PORT=8543
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: 'always'
    ports:
      - "8808:8808"