#!/usr/bin/.env bash

# 项目源码根目录
PROJECT_ROOT=$(dirname "${BASH_SOURCE[0]}")/..

# db 配置信息
export SOCIALSERVE_DB_HOST=${SOCIALSERVE_DB_HOST:-127.0.0.1} # MariaDB 主机地址
export SOCIALSERVE_DB_PORT=${SOCIALSERVE_DB_PORT:-5432} # MariaDB 主机地址
#export SOCIALSERVE_DB_DATABASE=${SOCIALSERVE_DB_DATABASE:tgtask} #
#export SOCIALSERVE_DB_USERNAME=${SOCIALSERVE_DB_USERNAME:} #  数据库用户名
#export SOCIALSERVE_DB_PASSWORD=${SOCIALSERVE_DB_PASSWORD:} #  数据库密码

# socialserver 配置
export IAM_CONFIG_DIR=${IAM_CONFIG_DIR:-/etc/iam} # iam 配置文件存放目录
export LOG_DIR=${LOG_DIR:-${PROJECT_ROOT}/../logs} # iam 日志文件存放目录
export CA_FILE=${CA_FILE:-${IAM_CONFIG_DIR}/cert/ca.pem} # CA   /etc/iam/cert/ca.pem

# socialserver 配置
export SOCIALSERVE_HOST=${SOCIALSERVE_HOST:-127.0.0.1} #
export SOCIALSERVE_CONFIG_PATH=${SOCIALSERVE_CONFIG_PATH:-${PROJECT_ROOT}/configs} #

export SOCIALSERVE_INSECURE_BIND_ADDRESS=${SOCIALSERVE_INSECURE_BIND_ADDRESS:-0.0.0.0}
export SOCIALSERVE_INSECURE_BIND_PORT=${SOCIALSERVE_INSECURE_BIND_PORT:-8808}

export SOCIALSERVE_SECURE_BIND_ADDRESS=${SOCIALSERVE_SECURE_BIND_ADDRESS:-0.0.0.0}
export SOCIALSERVE_SECURE_BIND_PORT=${SOCIALSERVE_SECURE_BIND_PORT:-8443}
export SOCIALSERVE_SECURE_TLS_CERT_KEY_CERT_FILE=${SOCIALSERVE_SECURE_TLS_CERT_KEY_CERT_FILE:-${PROJECT_ROOT}/configs/ca/cert/iam-apiserver.pem} #{IAM_CONFIG_DIR}=/etc/iam/
export SOCIALSERVE_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${SOCIALSERVE_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${PROJECT_ROOT}/configs/ca/cert/iam-apiserver-key.pem}

export SOCIALSERVE_LOG_OUTPUT_PATHS=${SOCIALSERVE_LOG_OUTPUT_PATHS:-${LOG_DIR}/SOCIALSERVE.log,stdout}
export SOCIALSERVE_LOG_ERROR_OUTPUT_PATHS=${SOCIALSERVE_LOG_ERROR_OUTPUT_PATHS:-${LOG_DIR}/SOCIALSERVE.error.log}


